name: Build

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      imagem: docker.io/cypress/browser

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - uses: mobile-dev-inc/action-maestro-cloud@v1.1.0
        with:
          api-key: e91b24be-0ea2-4bc0-801f-0d4f7993df54
          app-file: qafood.apk
